---
apiVersion: v1
kind: Pod
metadata:
  name: minio
  labels:
    app: web
spec:
  containers:
    - name: minio
      image: minio/minio
      ports:
        - containerPort: 9001
      command: ["mc"]
      args: ["ls"]